### ISSUE TITLE
woudl you please license this code?

### ISSUE THREAD

**Issue by joshlong** [aliakh/demo-sockets-io-nio-nio2#2]
I'd like to reprint some of your code and explanations (both with attributions) in a book I'm writing. Is it possible to license this code as something like Apache 2 licensed? It's a very useful resource. Thank you for sharing your knowledge and work.

**Comment by aliakh** [comment]
https://github.com/aliakh/demo-sockets-io-nio-nio2/blob/master/LICENSE

**Comment by aliakh** [comment]
https://github.com/aliakh/demo-sockets-io-nio-nio2/blob/master/LICENSE

**Comment by joshlong** [comment]
i see you have added the license. That solves my problem and is very kind of you. thank you!

**Comment by joshlong** [comment]
is there a place I can donate $ to support your open source work, by the way? As a way of reimbursing you for your excellent work?

**Comment by aliakh** [comment]
In Belarus we have a limited set of options for civil payments, especially from abroad. Try to make a payment to my bank card 5392 1412 3528 9755 or to its bank account BY68 ALFA 3014 302S 4H00 1027 0000.
